### ISSUE TITLE
[v2 QUESTION]: ValueError reported when searching hyperparameter space

### ISSUE THREAD

**Issue by DengFeng-Zuo** [chemprop/chemprop#1050]
**What are you trying to do?**
I tried to use command line to search for the optimal hyperparameters to optimize the performance of the model. But when I run 
`chemprop hpopt --data-path D:\OPV_project2\chemprop\chemprop_data.csv --task-type regression --search-parameter-keywords all --hpopt-save-dir results` 
There reported an ValueError.
`ValueError: could not convert string to float: 'CCCCCCC1=CCC(C2(c3ccc(CCCCCC)cc3)c3cc4c(cc3C3SC5=C(SC(/C=C6\\C(=O)c7ccccc7C6=C(C#N)C#N)C5)C32)C(c2ccc(CCCCCC)cc2)(c2ccc(CCCCCC)cc2)c2c-4sc3cc(/C=C4\\C(=O)c5ccccc5C4=C(C#N)C#N)sc23)C=C1'`

If you could offer some assistance, I would greatly appreciate it.

**Previous attempts**
If possible, provide some examples of what you've already tried and what the output was.

**Screenshots**
![微信截图1](https://github.com/user-attachments/assets/4bde6d95-5fc8-4444-9951-f639767c2849)
![微信截图2](https://github.com/user-attachments/assets/ef792ba5-f88f-463e-8285-1c91299a366e)

**Comment by DengFeng-Zuo** [comment]
The data in `chemprop_data.csv` is shown below
![Uploading 微信截图3.png…]()

**Comment by DengFeng-Zuo** [comment]
The data in `chemprop_data.csv` is shown below
![微信截图3](https://github.com/user-attachments/assets/429852e8-853d-4366-9bc9-e127575b39d1)

**Comment by shihchengli** [comment]
By default, it is assumed that the SMILES are in the first column and the targets are in the remaining columns. If you want to train on two molecules as input, you need to use `--smiles-columns <column1> <column2>` and `--target-columns <column_3> <column_4> ...` flags, respectively. Please refer to our documentation (https://chemprop.readthedocs.io/en/main/tutorial/cli/train.html#input-data).

**Comment by DengFeng-Zuo** [comment]
> By default, it is assumed that the SMILES are in the first column and the targets are in the remaining columns. If you want to train on two molecules as input, you need to use `--smiles-columns <column1> <column2>` and `--target-columns <column_3> <column_4> ...` flags, respectively. Please refer to our documentation (https://chemprop.readthedocs.io/en/main/tutorial/cli/train.html#input-data).

Thank you very much for your suggestion, but after I modified the command line instruction to  `chemprop hpopt --data-path D:\OPV_project2\chemprop\chemprop_data.csv --task-type regression --smiles-columns Donor_smiles Acceptor_smiles --target-columns PCE --search-parameter-keywords all --hpopt-save-dir results`  as you suggested, an new FileNotFoundError occurred.
![微信截图1](https://github.com/user-attachments/assets/6b74776c-e096-4993-a986-d001feea418e)
![微信截图2](https://github.com/user-attachments/assets/f95ba765-8cba-4e71-925d-68d51ff4bfff)
  
I haven't found any relevant solutions in the documentation. Could you please provide some assistance? Thank you for your time.

**Comment by shihchengli** [comment]
This is already reported in #1033 and is solved via #1034.

**Comment by DengFeng-Zuo** [comment]
> This is already reported in #1033 and is solved via #1034.

Thanks a lot for your help. I downgraded the version of PyTorch to 2.3.1, but still encountered the same FileNotFoundError. I noticed that you also encountered the same issue in the Linux system and made a fix, while I executed the above command line instruction in the Windows system. Is this problem related to the operating system?


At the same time, I also tried to do hyperparameter optimization work in Jupyter Notebook according to the document   [](https://github.com/chemprop/chemprop/blob/main/examples/hpopting.ipynb) . Due to the original document was a single component task, I adjusted the input-data to multi-component to accommodate my task, but a RuntimeError occurred.
![微信截图_1](https://github.com/user-attachments/assets/55cb4dd4-0819-4dd4-8d46-591728456d73)

The code changes I made were these：
```
chemprop_dir = Path.cwd()
input_path = chemprop_dir / "chemprop_data.csv"  # path to your data .csv file containing SMILES strings and target values
num_workers = 0 # number of workers for dataloader. 0 means using main process for data loading
smiles_columns = ['Donor_smiles', 'Acceptor_smiles'] # name of the column containing SMILES strings 
target_columns = ['PCE'] # list of names of the columns containing targets

hpopt_save_dir = Path.cwd() / "hpopt" # directory to save hyperopt results
hpopt_save_dir.mkdir(exist_ok=True)
```

```
all_data = [[data.MoleculeDatapoint.from_smi(smis[0], y) for smis, y in zip(smiss, ys)]]
all_data += [[data.MoleculeDatapoint.from_smi(smis[i]) for smis in smiss] for i in range(1, len(smiles_columns))]
```
```

featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer()

train_datasets = [data.MoleculeDataset(train_data[i], featurizer) for i in range(len(smiles_columns))]
val_datasets = [data.MoleculeDataset(val_data[i], featurizer) for i in range(len(smiles_columns))]
test_datasets = [data.MoleculeDataset(test_data[i], featurizer) for i in range(len(smiles_columns))]
```

```
train_mcdset = data.MulticomponentDataset(train_datasets)
scaler = train_mcdset.normalize_targets()

val_mcdset = data.MulticomponentDataset(val_datasets)
val_mcdset.normalize_targets(scaler)

test_mcdset = data.MulticomponentDataset(test_datasets)
```

**Comment by shihchengli** [comment]
The error message is quite useful. You likely ran `ray.init()` twice and will need to shut down the Ray process.

**Comment by DengFeng-Zuo** [comment]
> The error message is quite useful. You likely ran `ray.init()` twice and will need to shut down the Ray process.

Thanks a lot for your suggestion. I solved this problem by running  `ray.shutdown()`.

However, there still seem to be some errors during the hyperparameter optimization problem for multi-component task. First, I made adjustments for the input data based on the demo in [https://github.com/chemprop/chemprop/blob/main/examples/training_regression_multicomponent.ipynb](https://github.com/chemprop/chemprop/blob/main/examples/training_regression_multicomponent.ipynb). But when I run the following code, I get an AttributeError. 

Could you please offer some help? I've checked different kinds of config settings and the help manual in Documentation and there is no help for hyperparameter optimization in multi-component tasks.

```
ray.init()

scheduler = FIFOScheduler()

# Scaling config controls the resources used by Ray
scaling_config = ScalingConfig(
    num_workers=31,
    use_gpu=False, # change to True if you want to use GPU
)

# Checkpoint config controls the checkpointing behavior of Ray
checkpoint_config = CheckpointConfig(
    num_to_keep=1, # number of checkpoints to keep
    checkpoint_score_attribute="val_loss", # Save the checkpoint based on this metric
    checkpoint_score_order="min", # Save the checkpoint with the lowest metric value
)

run_config = RunConfig(
    checkpoint_config=checkpoint_config,
    storage_path=hpopt_save_dir / "ray_results", # directory to save the results
)

ray_trainer = TorchTrainer(
    lambda config: train_model(
        config, train_mcdset, val_mcdset, num_workers, scaler
    ),
    scaling_config=scaling_config,
    run_config=run_config,
)

search_alg = HyperOptSearch(
    n_initial_points=1, # number of random evaluations before tree parzen estimators
    random_state_seed=42,
)

# OptunaSearch is another search algorithm that can be used
# search_alg = OptunaSearch() 

tune_config = tune.TuneConfig(
    metric="val_loss",
    mode="min",
    num_samples=3, # number of trials to run
    scheduler=scheduler,
    search_alg=search_alg,
    trial_dirname_creator=lambda trial: str(trial.trial_id), # shorten filepaths
    
)

tuner = tune.Tuner(
    ray_trainer,
    param_space={
        "train_loop_config": search_space,
    },
    tune_config=tune_config,
)

# Start the hyperparameter search
results = tuner.fit()
```
![微信截图2](https://github.com/user-attachments/assets/85f80e28-706a-44fc-8188-4fd95a2182e2)
![微信截图3](https://github.com/user-attachments/assets/e6a51ce9-787e-4231-b98c-d466189d407f)
![微信截图4](https://github.com/user-attachments/assets/a9521dae-0e97-48bb-868d-6c31cb3da86a)

**Comment by shihchengli** [comment]
@DengFeng-Zuo I am glad it is helpful. Regarding the new issue, please open another issue on Github so it will be easier to check and notify others.

**Comment by DengFeng-Zuo** [comment]
> @DengFeng-Zuo I am glad it is helpful. Regarding the new issue, please open another issue on Github so it will be easier to check and notify others.

Sure. I described the problem in #1052 
Thank you for your suggestion and help!
